### ISSUE TITLE
Implement New Website Styleguide 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/libapps#26]
Add to Springshare tools concurrently with the deployment of the new website this summer. 

[WDS Styleguide](https://drive.google.com/file/d/1AgLHDP4WtKLHVWLtex7X0E7mgj97Cx0P/view?usp=sharing)

- [x] Header (including the "user" menu displayed in the upper right hand corner on large screens. 
- [x] Footer
- [x] Base colors
- [x] Base fonts

## Questions
1. Should we replicate the entire main menu?

**Comment by VickieKarasic** [comment]
We tried inserting the latest Lux release (5.3.0) on a LibGuides Group homepage ([Testing Group](https://libguides.princeton.edu/homepage-2020?auth_reload=1)) and had to add back in some CSS from the current site to get styling to look similar, but it's still not looking as expected with some margin issues in the header/footer and overall scrunched contents: 

![image](https://github.com/user-attachments/assets/639c100d-ac8e-473d-b18c-2f47704b23e6)

Once we get this Testing Group homepage working and inserted on the main [Research Guides](https://libguides.princeton.edu/) page, we'll want to also add the latest Lux to the header/footer for LibCal, LibAnswers, and LibWizard. 

We did have success adding the updated Lux to the [A-Z Databases](https://libguides.princeton.edu/az/databases) homepage in Guides with expected look & feel.

**Comment by VickieKarasic** [comment]
We successfully added version 5.3.1 to homepages for LibGuides (including A-Z Databases), LibCal, and LibAnswers. We are working on getting Lux to work in LibWizard; @sandbergja and @christinach are researching JS code to try to make this work.
