### ISSUE TITLE
Test Lux New Library Header in Springshare Updated Databases View

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/libapps#27]
Test the result of https://github.com/pulibrary/lux-design-system/issues/216 in springshare when this ticket is done.

**Comment by kevinreiss** [comment]
@VickieKarasic and I added lux to the new libguides look and feel config. It appears to be loading and we tried to inject the header/footer, but are stuck on this error in the js console. 

<img width="1689" alt="Screenshot 2024-06-04 at 2 49 48 PM" src="https://github.com/pulibrary/libapps/assets/278825/8c3cb50b-3524-43a1-9c7e-8174de09e606">

**Comment by sandbergja** [comment]
I wonder if it needs this doodad that we needed for the department blog: https://github.com/pulibrary/pulibrary.github.io/pull/34/files#diff-a1dfe54bb99ef136a84677407010718b24fa33a6ba895939cc2af97b98394ccd

**Comment by kevinreiss** [comment]
Thanks, adding the window.process statement did remove the console error, however the header/footer components aren't yet displaying.

**Comment by VickieKarasic** [comment]
@kevinreiss and I upgraded to Lux 5.3.0 and it is now displaying correctly on the A-Z Databases pages.
